# Practice Project 1.

In [85]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as missi
from mlxtend.plotting import plot_decision_regions 

import warnings
warnings.filterwarnings("ignore")

sns.set()

from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier
from xgboost import XGBClassifier
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, RandomizedSearchCV, cross_val_score
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler, OneHotEncoder, OrdinalEncoder
from imblearn.over_sampling import SMOTE

In [86]:
dataset = load_breast_cancer()
# dataset["feature_names"]

In [87]:
dataset = pd.DataFrame(dataset.data, columns=dataset["feature_names"])
dataset

     mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
0          17.99         10.38          122.80  ...                0.2654          0.4601                  0.11890
1          20.57         17.77          132.90  ...                0.1860          0.2750                  0.08902
2          19.69         21.25          130.00  ...                0.2430          0.3613                  0.08758
3          11.42         20.38           77.58  ...                0.2575          0.6638                  0.17300
4          20.29         14.34          135.10  ...                0.1625          0.2364                  0.07678
..           ...           ...             ...  ...                   ...             ...                      ...
564        21.56         22.39          142.00  ...                0.2216          0.2060                  0.07115
565        20.13         28.25          131.20  ...                0.1628          0.2572                  0.06637
566        16.60         28.08          108.30  ...                0.1418          0.2218                  0.07820
567        20.60         29.33          140.10  ...                0.2650          0.4087                  0.12400
568         7.76         24.54           47.92  ...                0.0000          0.2871                  0.07039

[569 rows x 30 columns]

In [88]:
# 1. Smote
# 2. Scaling.
# 3. Encoding.
# 4. Outliers.
# 5. Missing Value.

In [89]:
# dataset.info()
dataset.describe()

       mean radius  mean texture  mean perimeter  ...  worst concave points  worst symmetry  worst fractal dimension
count   569.000000    569.000000      569.000000  ...            569.000000      569.000000               569.000000
mean     14.127292     19.289649       91.969033  ...              0.114606        0.290076                 0.083946
std       3.524049      4.301036       24.298981  ...              0.065732        0.061867                 0.018061
min       6.981000      9.710000       43.790000  ...              0.000000        0.156500                 0.055040
25%      11.700000     16.170000       75.170000  ...              0.064930        0.250400                 0.071460
50%      13.370000     18.840000       86.240000  ...              0.099930        0.282200                 0.080040
75%      15.780000     21.800000      104.100000  ...              0.161400        0.317900                 0.092080
max      28.110000     39.280000      188.500000  ...              0.291000        0.663800                 0.207500

[8 rows x 30 columns]

In [91]:
# dataset["mean radius"] = pd.DataFrame(dataset["mean radius"].astype(str))
# # type(pd.DataFrame(dataset["age"]))

In [ ]:
dataset.info()

In [92]:
# dataset["mean radius"].str.split(".", expand=True).astype(int)

      0   1
0    17  99
1    20  57
2    19  69
3    11  42
4    20  29
..   ..  ..
564  21  56
565  20  13
566  16   6
567  20   6
568   7  76

[569 rows x 2 columns]

In [83]:
dataset.age

0        0.038075906433423026
1      -0.0018820165277906047
2         0.08529890629667548
3         -0.0890629393522567
4        0.005383060374248237
                ...
437       0.04170844488444244
438     -0.005514554978810025
439       0.04170844488444244
440     -0.045472477940023646
441     -0.045472477940023646
Name: age, Length: 442, dtype: object